services:
  hackathon-api-main:
    image: jocimsus/hackathon-api:latest
    container_name: hackathon-api-main
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "3333:3333"
    env_file:
      - .env

  hackathon-api-develop:
    image: jocimsus/hackathon-api:develop
    container_name: hackathon-api-develop
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "9999:3333"
    env_file:
      - .env
