services:
  hackathon-api-develop:
    image: jocimsus/hackathon-api:develop
    container_name: hackathon-api-develop
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "9999:3333"
    env_file:
      - .env.dev
